### ISSUE TITLE
Toast is not visible

### ISSUE THREAD

**Issue by Kranthikumar01** [devxoul/Toaster#224] opened 2024-08-29 11:17 UTC
Toast is not visible when attempted to call the the below function

```
static func makeToast(message: String) {
        Toast(text: message).show()
 }
```

as debugged in Toast class it is evident that completion block to hide the toast is executing very fast. please find the below attached screenshot

<img width="1196" alt="Screenshot 2024-09-03 at 12 19 49 PM" src="https://github.com/user-attachments/assets/ff17c9a4-0f6d-4544-8f11-8b5531264699">

but i can be able to observe this behaviour only for the first time of app launch

**Comment by Kranthikumar01** [comment] 2024-09-03 06:52
@Coeur could you please check this?

**Comment by Coeur** [comment] 2024-09-03 09:22
@devxoul may know more.
Since you said:
>but i can be able to observe this behaviour only for the first time of app launch

Then try to delay your Toast until after [`applicationDidFinishLaunching:`](https://developer.apple.com/documentation/appkit/nsapplicationdelegate/1428385-applicationdidfinishlaunching)?

**Comment by Coeur** [comment] 2024-09-03 11:36
Make sure you're on the latest commit from main/master branch.

Since there is a Demo app in the project, and that Demo app is not suffering from visibility issues, I'll close this issue.

Feel free to create a reproducible demo in order to re-open the issue.
```
===>Toast Starts Execution 2024-09-03 11:35:27 +0000 Duration:  2.0
===>Toast Ends Execution 2024-09-03 11:35:29 +0000 Duration:  2.0
===>Toast Starts Execution 2024-09-03 11:35:29 +0000 Duration:  2.0
===>Toast Ends Execution 2024-09-03 11:35:32 +0000 Duration:  2.0
===>Toast Starts Execution 2024-09-03 11:35:32 +0000 Duration:  3.5
===>Toast Ends Execution 2024-09-03 11:35:36 +0000 Duration:  3.5
===>Toast Starts Execution 2024-09-03 11:35:36 +0000 Duration:  5.0
===>Toast Ends Execution 2024-09-03 11:35:42 +0000 Duration:  5.0
```

**Closed by Coeur** 2024-09-03 11:36 UTC
