### ISSUE TITLE
Toast message view did not rotate on iPad mini.

### ISSUE THREAD

**Issue by suniljakhar** [devxoul/Toaster#81] opened 2016-05-25 13:05 UTC
In iPad mini (iOS 9.3.1), when we rotate device from portrait to landscape mode, toast message did not rotate with latest version of JLToast(1.4.1). In older JLToast(1.0), it is working fine. In iPad air the version of JLToast(1.4.1) also working as expected. Please find attach screenshot for more reference.

![img_0079](https://cloud.githubusercontent.com/assets/14994690/15540666/448b5778-22a6-11e6-923a-4fabcf29c916.PNG)

**Comment by devxoul** [comment] 2016-05-25 15:07
@suniljakhar, Thank you for report. Could you please let me know these:

0. Are you using LaunchScreen?
0. What is your orientation option & fullscreen requirement?

    This is an example:

    ![](https://cloud.githubusercontent.com/assets/263351/15384468/6a5ae4a6-1dcd-11e6-99c6-27087b334791.png)

Or you can provide your **`Info.plist`** file.

I think I have to reopen #79

**Comment by suniljakhar** [comment] 2016-05-27 06:21
Please find my answers
1. Yes
2. 
![screen shot 2016-05-27 at 11 46 18 am](https://cloud.githubusercontent.com/assets/14994690/15599440/d8b335a0-2400-11e6-98eb-8500b6842d98.png)

**Comment by devxoul** [comment] 2016-05-27 09:46
@suniljakhar, Thanks. I'll have a look for it soon :)

**Comment by suniljakhar** [comment] 2016-05-27 10:50
@devxoul Please look for it ASAP.

**Comment by devxoul** [comment] 2016-05-27 15:04
@suniljakhar, can you reproduce the bug with iPad Simulator?

**Comment by suniljakhar** [comment] 2016-05-31 13:41
Sorry for late reply, this issue is only reproducible on iPad mini(i.e older one). If you can arrange from somewhere that would be good, otherwise i will create a sample to reproduce it and send it to you.

**Comment by devxoul** [comment] 2016-06-01 02:27
@suniljakhar, That's odd. Could you reproduce the bug in iPad Simuator?

**Comment by suniljakhar** [comment] 2016-06-01 07:09
@devxoul  I have imported JLToast as 'github "devxoul/JLToast" ~> **1.4**' in Cartfile. Is it ok.
Please find attached sample project. In this sample, i am able to produce this issue in iPad Retina 9.3 simulator.
[scrollViewAmbigous-master 2.zip](https://github.com/devxoul/JLToast/files/292815/scrollViewAmbigous-master.2.zip)

**Comment by devxoul** [comment] 2016-06-02 06:13
@suniljakhar, Thanks! I can reproduce the bug. It either occurs in iPad Pro 9.3 too. I'll check this as soon as possible.

**Comment by suniljakhar** [comment] 2016-06-02 07:22
Thanks! Please look for it ASAP.

**Comment by suniljakhar** [comment] 2016-06-03 10:35
@devxoul Did you get time to look for it?

**Comment by devxoul** [comment] 2016-06-04 13:31
I think I need more time to investigate this issue. This is very odd :(

**Comment by suniljakhar** [comment] 2016-06-10 05:25
@devxoul 
What's the status of this?

**Comment by devxoul** [comment] 2016-06-10 05:34
@suniljakhar, There hasn't been much progress.

**Comment by suniljakhar** [comment] 2016-06-10 05:49
@devxoul 
It would be good for us, if you can look for it on priority because we are almost ready to release the product.

**Comment by devxoul** [comment] 2016-06-10 05:52
@suniljakhar, If you have don't have much time, I think you could use older version instead. My first priority is company work 😅

**Comment by r3nar** [comment] 2016-10-11 19:52
Same behavior with iPad 2 - iOS 9 only

**Comment by Burtan** [comment] 2017-01-03 14:26
I've also faced this issue on iPad3 iOS 9.3

**Comment by SnitramDev** [comment] 2017-01-25 18:00
Any news on this?

**Comment by devxoul** [comment] 2017-01-25 18:49
Not yet. I don't have much time too deal with this issue. I hope someone could contribute :)

**Comment by johnflightsteter** [comment] 2018-10-18 21:53
Also experiencing the exact same issue on an iPad 10.5 inch with iOS 12. Has there been a fix for this yet? Double checking to ensure I am not experiencing a new issue of some kind, or does something in the code need to be updated.

**Comment by cozzin** [comment] 2019-08-24 16:37
@suniljakhar @r3nar @Burtan @lmsmartins @johnflightsteter
Is there anyone who can reproduce this bug on the current master branch(3c8673d14466beee879a150b3423aaac6900577a) basis?
If you have a project that reproduces this bug, please attach it.
Also, if you tell us the os version and device name, it will be very helpful.

**Comment by cozzin** [comment] 2019-08-29 16:38
@Coeur I think it's okay to close the issue now. 
If anyone have the problem later, we can open this issue again.

**Comment by Coeur** [comment] 2019-08-30 04:24
@johnflightsteter Rotation seems to be working on our master branch Toaster official demo on Simulator iPad Pro 10.5 with iOS 12.4.
![Simulator Screen Shot - iPad Pro (10 5-inch) - 2019-08-30 at 12 20 54](https://user-images.githubusercontent.com/839992/63992900-ac342000-cb20-11e9-9e86-448e94bf0bd4.png)

Let us know in a new issue if there is a reproducible scenario where it doesn't work (physical device? different UI hierarchy?).

**Closed by Coeur** 2019-08-30 04:24 UTC
